[project]
name = "russ-swiss-tournament"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Joakim Weckman", email = "joakim.weckman@gmail.com" }
]
dependencies = [
    "fastapi",
    "sqlmodel",
    "uvicorn",
    "jinja2",
    "pytailwindcss",
    "python-multipart",
    "tomli",
]

[dependency-groups]
dev = [
    "pytest",
    "pytest-profiling",
    "pyinstrument",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
