[general]
title = "Tie-break test"
year = 2024
count = 24
rounds = 3
round_system = "swiss"
tie_break_methods_swiss =  [
  "modified_median",
  "solkoff"
]
folder = "test_tie_break"
round_folder = "rounds"

[management]
coordinator = "Dummy"
commitee_members = [
  "Dummy2",
]

[players]
ids = [
  0,
  1,
  2,
  3,
  4,
  5,
  6,
  7,
]

