title = "Dummy"

[management]
coordinator = "Dummy"
commitee_members = [
  "Dummy2",
]

[players]
ids = [
  1,
  2,
  3,
  4,
  5,
  6,
  7,
  8,
  9,
  10,
  11,
  12,
  13,
  14
]

[general]
year = 2023
count = 23
rounds = 9
tie_break_method = "modified_median"
folder = "dummy"

